name: Deploy to FTPS
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: corepack enable
      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '20'
      - run: pnpm install
      - run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4.5.0
        with:
          path: ./dist
  web-deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/download-artifact@v4.1.8
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTPSERVER }}
          username: ${{ secrets.FTPUSERNAME }}
          password: ${{ secrets.FTPPASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./artifact/
          server-dir: /public_html/
